### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Lextuga007** [sianbladon/Data-Viz#2]
There is no licence on your code but I'd like to use it with your permission. 

I've used your GIF for a presentation https://lextuga007.github.io/Presentations/spc-analysts/spc-presentation.html#1 for NHS analysts and given you credit but I love your GIF so much I wondered if it could be submitted to GIPHY? 

This was a great entry and your award was well deserved!

Thanks - Zoë

**Comment by sianbladon** [comment]
Hi Zoë, thank you for getting in touch and for your kind words!

Yes you can absolutely use the code! I didn't really know licenses were a thing... still pretty new to this. I'll look into putting it on GIPHY as well!

I have attended a few of the NHS-R webinars and part of the conference you put on last year, I think the work you guys do is great! 

Sian

**Comment by Lextuga007** [comment]
Hello

Thanks for replying so quickly and it's great that you come to the NHS-R webinars/conference! I'm hoping to do some more about GitHub as many analysts (including myself!) are really new to it. Licences can be added through the GitHub pages which is easy - happy to do a call to show you if you would like any help, might be good just to meet up anyway :)

Please let me know when you do the GIPHY as I know a couple of us on Twitter will definitely use it a lot!

Zoë

**Comment by sianbladon** [comment]
Hi Zoë,

sorry for taking so long to get back to you!

I've uploaded the gif onto GIPHY, hopefully you can see that here: https://giphy.com/channel/sianbladon
I've tagged it with #rstats #ggplot2 #gganimate #floviz #florence nightingale and #coxcomb
It's not showing up when I search using those tags but apparently it can take up to a week so maybe I'm just being impatient...

I've been meaning to learn more about GitHub for ages but I keep on putting it off as it's so unfamiliar. A call would be great if the offer is still open :) 

Sian

**Comment by Lextuga007** [comment]
Yay! Definitely open for a GitHub chat. I'll DM you in Twitter...

**Comment by Lextuga007** [comment]
I can see a licence so closing :) 🥇
